# Generated by Django 5.2.3 on 2025-06-22 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CinetPayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID Transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('description', models.TextField(verbose_name='Description')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nom client')),
                ('customer_surname', models.CharField(max_length=100, verbose_name='Prénom client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email client')),
                ('customer_phone_number', models.CharField(max_length=20, verbose_name='Téléphone client')),
                ('customer_address', models.CharField(max_length=200, verbose_name='Adresse client')),
                ('customer_city', models.CharField(max_length=100, verbose_name='Ville client')),
                ('customer_country', models.CharField(default='CI', max_length=2, verbose_name='Pays client')),
                ('customer_state', models.CharField(default='CI', max_length=2, verbose_name='État client')),
                ('customer_zip_code', models.CharField(max_length=10, verbose_name='Code postal client')),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de paiement')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='URL de paiement')),
                ('cinetpay_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction CinetPay')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('metadata', models.TextField(blank=True, verbose_name='Métadonnées')),
                ('invoice_data', models.JSONField(blank=True, default=dict, verbose_name='Données facture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_payments', to='depannage.repairrequest', verbose_name='Demande de réparation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement CinetPay',
                'verbose_name_plural': 'Paiements CinetPay',
                'ordering': ['-created_at'],
            },
        ),
    ]
