# Generated by Django 5.2.4 on 2025-07-14 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de support',
                'verbose_name_plural': 'Demandes de support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='locationhistory',
            constraint=models.CheckConstraint(condition=models.Q(('heading__isnull', True), models.Q(('heading__gte', 0), ('heading__lte', 360)), _connector='OR'), name='location_history_heading_valid'),
        ),
        migrations.AddConstraint(
            model_name='locationhistory',
            constraint=models.CheckConstraint(condition=models.Q(('battery_level__isnull', True), models.Q(('battery_level__gte', 0), ('battery_level__lte', 100)), _connector='OR'), name='location_history_battery_valid'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
