# Generated by Django 5.1.7 on 2025-06-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0002_cinetpaypayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianlocation',
            options={'verbose_name': 'Localisation de technicien', 'verbose_name_plural': 'Localisations des techniciens'},
        ),
        migrations.RemoveField(
            model_name='technicianlocation',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='technicianlocation',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='technicianlocation',
            name='technician',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='depannage.technician'),
        ),
        migrations.AddIndex(
            model_name='technicianlocation',
            index=models.Index(fields=['technician'], name='depannage_t_technic_cdad4b_idx'),
        ),
    ]
