# Generated by Django 5.2.3 on 2025-07-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0005_repairrequest_city_repairrequest_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('support_email', models.EmailField(max_length=254)),
                ('default_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=50)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('min_payout_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('max_interventions_per_day', models.IntegerField(default=10)),
                ('service_radius_km', models.FloatField(default=20.0)),
                ('cancelation_deadline_hours', models.IntegerField(default=2)),
                ('enable_geolocation_map', models.BooleanField(default=True)),
                ('default_map_provider', models.CharField(default='OpenStreetMap', max_length=50)),
                ('theme_color', models.CharField(default='#2563eb', max_length=20)),
                ('enable_2fa_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
