# Generated by Django 5.2.3 on 2025-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0007_clientlocation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientlocation',
            new_name='depannage_c_client__916d09_idx',
            old_name='depannage_client_idx',
        ),
        migrations.AlterField(
            model_name='clientlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='clientlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
