# Generated by Django 5.2.3 on 2025-07-07 02:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0009_alter_repairrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Standard', max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='depannage.payment')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='depannage.technician')),
            ],
            options={
                'verbose_name': 'Abonnement technicien',
                'verbose_name_plural': 'Abonnements techniciens',
                'ordering': ['-end_date'],
            },
        ),
    ]
