# Generated by Django 5.2.3 on 2025-07-07 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0011_repairrequest_mission_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinetpaypayment',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_payments', to='depannage.repairrequest'),
        ),
    ]
