# Generated by Django 5.2.3 on 2025-07-09 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '0015_adminnotification_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='Durée en mois')),
                ('payment_method', models.CharField(default='manual_validation', max_length=50, verbose_name='Méthode de paiement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Notes de validation')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='depannage.techniciansubscription')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payment_requests', to='depannage.technician')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande de paiement d'abonnement",
                'verbose_name_plural': "Demandes de paiement d'abonnement",
            },
        ),
    ]
