# Generated by Django 5.2.3 on 2025-07-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '10001_cinetpaypayment_notification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
