# Generated by Django 5.2.3 on 2025-07-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depannage', '10000_alter_techniciansubscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinetpaypayment',
            name='notification_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Notification brute CinetPay'),
        ),
    ]
