# Generated by Django 5.2.3 on 2025-07-03 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_address_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('event_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('profile_update', 'Modification profil'), ('password_change', 'Changement mot de passe'), ('payment', 'Paiement'), ('account_delete', 'Suppression de compte'), ('otp_sent', 'OTP envoyé'), ('otp_verified', 'OTP vérifié'), ('session_revoke', 'Session révoquée')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geo_country', models.CharField(blank=True, max_length=64)),
                ('geo_city', models.CharField(blank=True, max_length=64)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
