# Generated by Django 5.2.3 on 2025-07-07 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('carte_identite', "Carte d'identité nationale"), ('carte_biometrique', 'Carte biométrique'), ('passeport', 'Passeport'), ('certificat_residence', 'Certificat de résidence')], max_length=32)),
                ('fichier', models.FileField(upload_to='pieces_jointes/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe justificative',
                'verbose_name_plural': 'Pièces jointes justificatives',
                'ordering': ['-date_upload'],
            },
        ),
    ]
