# Generated by Django 5.2.3 on 2025-07-07 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_piecejointe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_identite', models.FileField(upload_to='technician_docs/')),
                ('certificat_residence', models.FileField(upload_to='technician_docs/')),
                ('specialty', models.CharField(max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
