# Generated by Django 5.2.3 on 2025-07-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_technicianprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecejointe',
            name='fichier',
            field=models.FileField(upload_to='technician_docs/'),
        ),
    ]
