# Generated by Django 5.2.3 on 2025-07-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_piecejointe_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
